<?php

namespace AppBundle\Repository;

/**
 * LotteryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotteryRepository extends \Doctrine\ORM\EntityRepository
{
}
